server:
  port: 8000
  servlet:
    context-path: /boot

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/et1910?serverTimezone=UTC
    username: root
    password: etoak
    hikari:
      maximum-pool-size: 50

  thymeleaf:
    cache: false
    encoding: UTF-8
    servlet:
      multipart:
        # 默认1MB
        max-file-size: 2MB


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.etoak.bean

pagehelper:
  reasonable: true

# 打印sql
logging:
  level:
    com.etoak.mapper: DEBUG

#自定义配置：文件上传和图片访问
upload:
  dir: d:/upload/
  savePathPrefix: /pics/
  mapping: /pics/**